name: Continuos Integration


on: pull_request

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: action/setup-node@v2
        with: 
          node-version: 22.
      - name: run install, build and test
        run: 
          npm install
          npm run build
          npm run test